version: '3'

services:
  router1:
    build: .
    ports:
      - "8081:8080"  # Первый сервер на порту 8081
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=router_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./sentinel2_archive:/app/sentinel2_archive
      - router1_data:/var/lib/postgresql  # Отдельный том для БД первого сервера

  router2:
    build: .
    ports:
      - "8082:8080"  # Второй сервер на порту 8082
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=router_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./sentinel2_archive:/app/sentinel2_archive
      - router2_data:/var/lib/postgresql  # Отдельный том для БД второго сервера

  router3:
    build: .
    ports:
      - "8083:8080"  # Третий сервер на порту 8083
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=router_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./sentinel2_archive:/app/sentinel2_archive
      - router3_data:/var/lib/postgresql  # Отдельный том для БД третьего сервера

volumes:
  router1_data:  # Том для данных БД первого сервера
  router2_data:  # Том для данных БД второго сервера
  router3_data:  # Том для данных БД третьего сервера

networks:
  router_network:
    driver: bridge 